"""Regenerate BabyLM training and evaluation inputs from pinned public sources."""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import shutil
import subprocess
import sys
import tempfile

from huggingface_hub import hf_hub_download, snapshot_download
import numpy as np
import tiktoken

from .io import sha256_file, atomic_json
from .spec import MANIFEST_SHA256, CHECKPOINT_INPUT_SHA256, CORPUS_REVISION, EVALUATION_REVISION, EVALUATOR_REVISION, SPEC, STREAM_SEED
from .data import BabyLMData, BabyLMEvaluationData, _records
from .pack_evaluation import (prepare_zero_shot, prepare_finetune, GLOBAL_PIQA_PARALLEL,
                              GLOBAL_PIQA_PARALLEL_REVISION, GLOBAL_PIQA_NONPARALLEL,
                              GLOBAL_PIQA_NONPARALLEL_REVISION)

ROOT = Path(__file__).resolve().parents[2]
TRAINING_IDENTITY = ROOT / "data/babylm-input-manifest.json"
EVALUATION_IDENTITY = ROOT / "data/babylm-evaluation-records.json"


def verify_records(root: Path, metadata: dict) -> None:
    for row in _records(metadata):
        path = (root / row["path"]).resolve()
        if root.resolve() not in path.parents:
            raise ValueError("input record escapes its root")
        if path.stat().st_size != row["bytes"] or sha256_file(path) != row["sha256"]:
            raise ValueError(f"generated input differs from its recorded checksum: {row['path']}")


def encode_corpus(sources: list[tuple[Path, dict]], output: Path) -> None:
    encoder = tiktoken.get_encoding("gpt2")
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("wb") as destination:
        for path, identity in sources:
            if sha256_file(path) != identity["source_sha256"] or path.stat().st_size != identity["source_bytes"]:
                raise ValueError(f"BabyLM source identity changed: {path.name}")
            rows = tokens = 0
            with path.open(encoding="utf-8") as handle:
                while True:
                    lines = [handle.readline() for _ in range(4096)]
                    texts = [line.rstrip("\r\n") for line in lines if line]
                    if not texts:
                        break
                    for encoded in encoder.encode_ordinary_batch(texts, num_threads=8):
                        values = np.asarray([*encoded, 50256], dtype="<u2")
                        values.tofile(destination)
                        tokens += len(values)
                    rows += len(texts)
            if rows != identity["rows"] or tokens != identity["gpt2_tokens_including_eot"]:
                raise ValueError(f"BabyLM tokenization changed: {path.name}")
            print(json.dumps({"phase": "prepare_corpus", "source": path.name, "rows": rows}), flush=True)


def prepare_training(output: Path) -> None:
    if sha256_file(TRAINING_IDENTITY) != MANIFEST_SHA256:
        raise ValueError("declared training manifest changed")
    if (output / "manifest.json").exists():
        BabyLMData(output / "manifest.json", output)
        return
    manifest = json.loads(TRAINING_IDENTITY.read_text())
    sources = [(Path(hf_hub_download("BabyLM-community/BabyLM-2026-Strict", row["name"],
                                    repo_type="dataset", revision=CORPUS_REVISION)), row)
               for row in manifest["corpus"]["source_summaries"]]
    output.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(dir=output, prefix=".build-") as temporary:
        for index in range(2):
            build = Path(temporary) / str(index)
            encode_corpus(sources, build / "corpus/train_tokens.uint16.bin")
            starts = np.concatenate([
                np.random.Generator(np.random.PCG64(STREAM_SEED + 1_000_003 * epoch))
                .permutation(82281).astype("<u8") * np.uint64(SPEC.context_length)
                for epoch in range(SPEC.passes)
            ])
            np.save(build / "corpus/train_starts.uint64.npy", starts, allow_pickle=False)
            verify_records(build, manifest)
        if (output / "corpus").exists():
            raise FileExistsError("unverified corpus already exists")
        shutil.move(str(Path(temporary) / "0/corpus"), output / "corpus")
    # This is an input manifest, copied only after all generated bytes match it.
    shutil.copyfile(TRAINING_IDENTITY, output / "manifest.json")
    BabyLMData(output / "manifest.json", output)


def evaluation_sources() -> tuple[Path, Path, Path]:
    official = Path(snapshot_download("BabyLM-community/BabyLM-2026-Strict-Evals",
                                     repo_type="dataset", revision=EVALUATION_REVISION,
                                     allow_patterns=["evaluation_data/**"]))
    parallel = Path(hf_hub_download(GLOBAL_PIQA_PARALLEL, "data/parallel_eng_latn.tsv",
                                   repo_type="dataset", revision=GLOBAL_PIQA_PARALLEL_REVISION))
    nonparallel = Path(hf_hub_download(GLOBAL_PIQA_NONPARALLEL, "data/nonparallel_eng_latn.tsv",
                                      repo_type="dataset", revision=GLOBAL_PIQA_NONPARALLEL_REVISION))
    return official, parallel, nonparallel


def prepare_core(output: Path) -> None:
    destination = output / "evaluation/packed"
    expected = json.loads(EVALUATION_IDENTITY.read_text())
    official, parallel, nonparallel = evaluation_sources()
    human_root = output / "official-source/evaluation_data/full_eval"
    for relative in ("reading/reading_data.csv", "aoa/cdi_human.csv"):
        destination_file = human_root / relative
        destination_file.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(official / "evaluation_data/full_eval" / relative, destination_file)
    if (output / "evaluation/manifest.json").exists():
        verify_records(destination, expected)
        return
    output.mkdir(parents=True, exist_ok=True)
    encoder = tiktoken.get_encoding("gpt2")
    with tempfile.TemporaryDirectory(dir=output, prefix=".evaluation-") as temporary:
        for index in range(2):
            build = Path(temporary) / str(index)
            build.mkdir()
            zero = prepare_zero_shot(official, parallel, nonparallel, build, encoder, maximum_sequence_length=2048)
            fine = prepare_finetune(official, build, encoder, maximum_sequence_length=512, seed=42)
            if zero != expected["zero_shot"] or fine != expected["finetune"]:
                raise ValueError("regenerated BabyLM evaluation metadata changed")
            verify_records(build, expected)
        if destination.exists():
            raise FileExistsError(destination)
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(Path(temporary) / "0"), destination)
    shutil.copyfile(EVALUATION_IDENTITY, output / "evaluation/manifest.json")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--stage", choices=("training", "core", "checkpoints", "full-ewok", "check"), required=True)
    parser.add_argument("--evaluator-root", type=Path)
    args = parser.parse_args()
    output = args.output.resolve()
    if args.stage == "training":
        prepare_training(output)
    elif args.stage == "core":
        prepare_core(output)
    elif args.stage == "check":
        BabyLMData(output / "manifest.json", output)
        BabyLMEvaluationData(output / "manifest.json", output)
    elif args.stage == "checkpoints":
        official, parallel, nonparallel = evaluation_sources()
        target = output / "checkpoint-evaluation"
        if target.exists():
            if sha256_file(target / "manifest.json") != CHECKPOINT_INPUT_SHA256:
                raise ValueError("checkpoint input identity changed")
            verify_records(target, json.loads((target / "manifest.json").read_text()))
            return
        hashes = []
        for index in range(2):
            build = output / f".checkpoint-build-{index}"
            subprocess.run([sys.executable, "-m", "reproduction.babylm.prepare_checkpoint_evaluation",
                            "--official-root", str(official / "evaluation_data"),
                            "--global-parallel", str(parallel), "--global-nonparallel", str(nonparallel),
                            "--output", str(build)], check=True)
            hashes.append(sha256_file(build / "manifest.json"))
        if hashes != [CHECKPOINT_INPUT_SHA256] * 2:
            raise ValueError("checkpoint evaluation duplicate builds differ")
        if target.exists():
            raise FileExistsError(target)
        shutil.move(str(output / ".checkpoint-build-0"), target)
        shutil.rmtree(output / ".checkpoint-build-1")
    else:
        if args.evaluator_root is None:
            parser.error("full-ewok requires --evaluator-root at the pinned official revision")
        from .score_human_likeness import require_evaluator_revision
        require_evaluator_revision(args.evaluator_root)
        expected = json.loads((ROOT / "data/babylm-ewok-records.json").read_text())
        if (output / "full-ewok/manifest.json").exists():
            verify_records(output / "full-ewok", expected)
            return
        output.mkdir(parents=True, exist_ok=True)
        with tempfile.TemporaryDirectory(dir=output, prefix=".ewok-") as temporary:
            for index in range(2):
                build = Path(temporary) / str(index)
                subprocess.run([sys.executable, "-m", "reproduction.babylm.prepare_full_ewok",
                                "--vocab", str(args.evaluator_root / "strict/evaluation_pipeline/ewok/vocab.txt"),
                                "--nltk-data", str(output / "nltk"), "--output", str(build),
                                "--archive", str(Path(temporary) / f"{index}.tar")], check=True)
                generated = json.loads((build / "manifest.json").read_text())
                if {key: generated[key] for key in expected} != expected:
                    raise ValueError("full EWoK prepared records differ from the recorded evaluation")
                verify_records(build, expected)
            shutil.move(str(Path(temporary) / "0"), output / "full-ewok")
    print(json.dumps({"status": "inputs_prepared", "stage": args.stage}), flush=True)


if __name__ == "__main__":
    main()
